### ISSUE TITLE
Can macro-ts do side-effect in code generation ?

### ISSUE THREAD

**Issue by xialvjun** [blainehansen/macro-ts#1]
like
```ts
let result = await sql!!;{select * from person where name='abc'};

// it generates code ... PersonStruct is generated by query the db table structure
interface PersonStruct {
  id: number;
  name: string;
  age: number;
}
let result = await sql<PersonStruct>(`select * from person where name='abc'`);
// result is PersonStruct[]
```

**Comment by blainehansen** [comment]
Yeah, the macros can be completely arbitrary :) you can read files, query databases, make network calls, send requests to the moon if you want ha. 

Although this makes me realize, macros should probably be asynchronous by default so these things can be done in an ergonomic way.... unfortunately the typescript compiler isn't asynchronous so we won't get the full performance benefit, but that doesn't really matter.

That's probably one of the next things I'll do, allowing asynchronous macros :)
